---
- name: phantomjs2 dependencies
action: apt pkg={{item}} state=present
with_items:
  - build-essential
  - g++
  - flex
  - bison
  - gperf
  - ruby
  - perl
  - libsqlite3-dev
  - libfontconfig1-dev
  - libicu-dev
  - libfreetype6
  - libssl-dev
  - libpng-dev
  - libjpeg-dev
  - python
